import Link from "next/link";
import { ArrowRight, BarChart3, BookOpen, ChevronRight, MessageCircle, PenLine, Play, Sparkles, Target } from "lucide-react";
import type { LucideIcon } from "lucide-react";

const features: { icon: LucideIcon; title: string; text: string }[] = [
  { icon: BookOpen, title: "Practice with purpose", text: "Targeted sessions that train exactly the skill behind your next band score." },
  { icon: PenLine, title: "Clearer writing feedback", text: "See what makes an answer stronger — structure, vocabulary, and task response." },
  { icon: BarChart3, title: "Progress you can feel", text: "A calm dashboard that turns your hard work into a plan you can trust." },
];

export default function LandingPage() {
  return <main className="landing"><nav className="landing-nav"><Link href="/" className="brand"><span className="brand-mark">i</span><span>just an <strong>IELTS</strong></span></Link><div className="landing-links"><a href="#how-it-works">How it works</a><a href="#why-us">Why us</a><Link href="/dashboard/vocabulary">Vocabulary</Link></div><div className="landing-actions"><Link className="text-link" href="/login">Log in</Link><Link className="nav-cta" href="/login">Start for free <ArrowRight size={15} /></Link></div></nav>
    <section className="landing-hero"><div className="hero-dot dot-one" /><div className="hero-dot dot-two" /><div className="hero-intro"><div className="eyebrow"><Sparkles size={14} /> IELTS prep, made more human</div><h1>Practice with clarity.<br /><em>Arrive with confidence.</em></h1><p>A considered IELTS workspace for learners who want a better score — without the overwhelm, noise, or guesswork.</p><div className="hero-buttons"><Link href="/login" className="dark-button">Build my study plan <ArrowRight size={18} /></Link><a href="#how-it-works" className="watch-link"><span><Play size={14} fill="currentColor" /></span> See how it works</a></div><div className="tiny-proof"><div className="face-stack"><i>F</i><i>A</i><i>M</i></div><span>Built for focused learners<br /><strong>aiming for Band 7+</strong></span></div></div>
      <div className="landing-preview"><div className="preview-top"><span className="preview-brand"><b>i</b> just an IELTS</span><span className="preview-date">Tuesday, Sep 22</span></div><div className="preview-body"><aside><span className="active">⌂ <b>Overview</b></span><span>◎ Practice hub</span><span>▤ Vocabulary</span><span>◌ Profile</span></aside><div className="preview-main"><p>Good morning, Fatima.</p><h2>Your next strong result<br />starts today.</h2><div className="preview-focus"><div><small>✦ TODAY&apos;S FOCUS</small><strong>Reading speed &amp;<br />academic vocabulary</strong><span>35 minute guided session</span></div><button><Play size={15} fill="currentColor" /> Start</button></div><div className="preview-stats"><span><small>STREAK</small><b>12 days</b></span><span><small>TARGET</small><b>Band 8.0</b></span><span><small>THIS WEEK</small><b>4.2 hours</b></span></div></div></div></div></section>
    <section id="how-it-works" className="steps-section"><p className="section-kicker">A better way to prepare</p><h2>Less noise. More <em>meaningful</em> practice.</h2><div className="steps"><article><span>01</span><h3>Set a goal that matters</h3><p>Tell us where you are and where you want to go. We&apos;ll help you see a clear path between them.</p></article><article><span>02</span><h3>Show up for focused sessions</h3><p>Small, intentional practice blocks make it easy to build a study rhythm that lasts.</p></article><article><span>03</span><h3>Know what to do next</h3><p>Track your skill growth and let your next best step reveal itself, one session at a time.</p></article></div></section>
    <section id="why-us" className="feature-section"><div><p className="section-kicker">Designed around your goal</p><h2>Everything you need.<br /><em>Nothing you don&apos;t.</em></h2><p className="feature-lead">The right tools, thoughtful guidance, and an uncluttered space to do your best work.</p><Link href="/login" className="simple-link">Explore your workspace <ChevronRight size={17} /></Link></div><div className="feature-list">{features.map(({ icon: FeatureIcon, title, text }) => <article key={title}><span><FeatureIcon size={21} /></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="quote-section"><MessageCircle size={27} /><blockquote>“The platform doesn&apos;t just tell me to work harder. It tells me what to work on, and that changed everything.”</blockquote><p>— IELTS learner, target Band 7.5</p></section>
    <section className="closing"><Target size={25} /><h2>Your score is a story<br />you can start changing today.</h2><Link href="/login" className="dark-button">Start preparing for free <ArrowRight size={18} /></Link></section>
    <footer><Link href="/" className="brand"><span className="brand-mark">i</span><span>just an <strong>IELTS</strong></span></Link><span>Focused preparation for meaningful results.</span><span>© 2026</span></footer></main>;
}
