import Link from 'next/link'
import { ArrowUpRight, CheckCircle2, Clock3, Headphones, Mic2, PenLine, BookOpen, Play } from 'lucide-react'
const skillData = [
  { label: 'Listening', detail: 'Section 3 · Academic', score: '7.0', color: 'sky', icon: Headphones, href: '/dashboard/listening' },
  { label: 'Reading', detail: 'Matching headings', score: '6.5', color: 'orange', icon: BookOpen, href: '/dashboard/reading' },
  { label: 'Writing', detail: 'Task 2 · Opinion essay', score: '7.0', color: 'violet', icon: PenLine, href: '/dashboard/writing' },
  { label: 'Speaking', detail: 'Part 2 · Cue card', score: '7.5', color: 'green', icon: Mic2, href: '/dashboard/speaking' },
]
export function PracticePage({ title = 'Good morning, Alex.', subtitle = 'Here is a clear path towards your target band.' }: { title?: string, subtitle?: string }) { return <>
  <div className="page-heading"><div><p className="eyebrow">Friday, 26 September</p><h1>{title}</h1><p>{subtitle}</p></div><Link className="primary-action" href="/dashboard/practice"><Play size={16} fill="currentColor"/> Start a practice</Link></div>
  <section className="goal-banner"><div className="goal-copy"><span className="soft-icon"><TargetIcon /></span><div><p>Target band score <b>7.5</b></p><small>You are <strong>0.5 band</strong> away. Keep this week&apos;s streak going.</small></div></div><div className="goal-progress"><div><span>Overall readiness</span><b>68%</b></div><div className="progress-track"><i style={{width:'68%'}} /></div></div><Link href="/dashboard/progress" className="text-link">View progress <ArrowUpRight size={15}/></Link></section>
  <section><div className="section-title"><div><h2>Continue where you left off</h2><p>Short, focused practice that fits your day.</p></div><Link href="/dashboard/practice">See all practice <ArrowUpRight size={15}/></Link></div><div className="skill-grid">{skillData.map(({label, detail, score, color, icon: Icon, href}) => <Link href={href} className="skill-card" key={label}><div className={`skill-icon ${color}`}><Icon size={22}/></div><div className="skill-card-head"><span>Latest band</span><b>{score}</b></div><h3>{label}</h3><p>{detail}</p><div className="card-footer"><span><Clock3 size={14}/> 15 min</span><ArrowUpRight size={17}/></div></Link>)}</div></section>
  <section className="dashboard-columns"><div className="glass-card focus-card"><div className="section-title"><div><p className="eyebrow">Today&apos;s focus</p><h2>Make your ideas easier to follow.</h2></div><span className="pill">12 min</span></div><p>Practice linking your main ideas with precise, natural transitions.</p><div className="focus-list"><span><CheckCircle2 size={17}/> Build a stronger paragraph flow</span><span><CheckCircle2 size={17}/> Get instant clarity feedback</span></div><Link href="/dashboard/writing" className="dark-link">Begin writing task <ArrowUpRight size={15}/></Link></div><div className="glass-card activity-card"><div className="section-title"><div><h2>Recent activity</h2><p>Your latest sessions</p></div><Link href="/dashboard/history-points">History</Link></div>{[['Writing task 2','Band 7.0','Today, 09:40'],['Listening: section 2','8 / 10 correct','Yesterday'],['Speaking cue card','Band 7.5','Wed, 24 Sep']].map(([a,b,c])=><div className="activity-row" key={a}><span className="activity-dot"/><div><b>{a}</b><small>{c}</small></div><strong>{b}</strong></div>)}</div></section>
</> }
function TargetIcon(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="m17 7 4-4"/></svg>}
